config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

   resources :courses

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses=Course.all
	end
	def new
		@course=Course.new
	end

	def create
		@course=Course.new(course_params)
		if @course.save
			redirect_to root_path
		else
			render :new
		end
	
	end

	private
	def course_params
		params.require(:course).permit(:title,:professor,:class,:credit)
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/courses/index.html.erb
<h2>Course Information</h2>

<% @courses.each do|course|%>
<%= link_to "course.title", courses_path(course) %>
<%end%>

app/views/courses/new.html.erb
<h2>New Course</h2>
<%= form_for @course do|f|%>
<div>
Course Title
	<%=f.text_field :title %>

</div>

<div>
Professor
	<%=f.text_field :professor %>
</div>

<div>
Class
	<%=f.text_field :class %>
</div>
<div>
Credit
	<%=f.text_field :credit %>
</div>

<%=f.submit%>
<%end%>

app/views/home/index.html.erb
<h2>Course Search</h2>
<%= link_to "New Course", new_course_path %>
<%= link_to "Course Information", courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Search</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>